[package]
name = "yt-rss-enhancer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
attohttpc = "0.28.2"
rouille = "3.6.2"
chrono = { version = "0.4.39", features = ["serde"] }
xmltree = "0.11.0"
